sudo: required
services:
  - docker

before_install:
  - docker build -t lrodrigo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lrodrigo/react-test npm test -- --coverage

after_success:
  - docker build -t lrodrigo/multi-client ./client
  - docker build -t lrodrigo/multi-nginx ./nginx
  - docker build -t lrodrigo/multi-server ./server
  - docker build -t lrodrigo/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push lrodrigo/multi-client
  - docker push lrodrigo/multi-nginx
  - docker push lrodrigo/multi-server
  - docker push lrodrigo/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-740211342396
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
